CREATE TABLE CUSTOMER (
CUS_CODE INT NOT NULL UNIQUE, 
CUS_LNAME VARCHAR(25),
CUS_FNAME VARCHAR(25),
CUS_AREACODE SMALLINT DEFAULT '859',
CUS_PHONE CHAR(7),
CUS_BALANCE NUMERIC(9,2) DEFAULT 0.00,
PRIMARY KEY(CUS_CODE)
);

CREATE TABLE INVOICE (
INV_NUM INT NOT NULL UNIQUE,
CUS_CODE INT,
INV_DATE DATE,
PRIMARY KEY (INV_NUM),
FOREIGN KEY (CUS_CODE) REFERENCES CUSTOMER(CUS_CODE) ON UPDATE CASCADE,
CONSTRAINT date_ctr CHECK(INV_DATE > '2000-01-01')
);

CREATE TABLE VENDOR (
V_CODE INT NOT NULL UNIQUE,
V_NAME VARCHAR(25),
V_CONTACT VARCHAR(25),
V_ACODE INT,
V_PHONE CHAR(7),
V_STATE CHAR(2),
V_ORDER INT,
PRIMARY KEY (V_CODE)
);

CREATE TABLE PRODUCT (
P_CODE INT NOT NULL UNIQUE,
P_DESC VARCHAR(25),
P_INDATE DATE,
P_QOH NUMERIC(9,2),
P_MIN NUMERIC(9,2),
P_PRICE NUMERIC(9,2),
P_DISCOUNT NUMERIC(9,2),
V_CODE INT,
PRIMARY KEY (P_CODE),
FOREIGN KEY (V_CODE) REFERENCES VENDOR (V_CODE) ON UPDATE CASCADE,
CONSTRAINT price CHECK (P_PRICE >= 0)
);

CREATE TABLE LINE (
INV_NUM INT NOT NULL UNIQUE,
LINE_NUMBER INT NOT NULL UNIQUE,
P_CODE INT,
LINE_UNITS NUMERIC,
LINE_PRICE NUMERIC,
PRIMARY KEY (INV_NUM, LINE_NUMBER),
FOREIGN KEY (INV_NUM) REFERENCES INVOICE (INV_NUM) ON DELETE CASCADE,
FOREIGN KEY (P_CODE) REFERENCES PRODUCT (P_CODE) ON UPDATE CASCADE,
CONSTRAINT min_price CHECK (LINE_PRICE > 0)
);

CREATE TABLE EMPLOYEE (
EMP_NUM INT NOT NULL UNIQUE,
EMP_LNAME VARCHAR(25),
PRIMARY KEY (EMP_NUM)
);

CREATE TABLE EDUCATION (
EDU_CODE INT NOT NULL UNIQUE,
EDU_DESCRIPTION VARCHAR (25),
PRIMARY KEY (EDU_CODE)
);

CREATE TABLE EMP_EDU (
EDU_CODE INT NOT NULL UNIQUE,
EMP_NUM INT NOT NULL UNIQUE,
EMP_EDU_DATE DATE,
PRIMARY KEY (EDU_CODE, EMP_NUM),
FOREIGN KEY (EDU_CODE) REFERENCES EDUCATION (EDU_CODE) ON DELETE CASCADE,
FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE (EMP_NUM) ON DELETE CASCADE
);










